version: '3.9'

services:
  app:
    build:
      context: .
      dockerfile: docker/Dockerfile
    ports:
      - "8080:8080"
    environment:
      DB_URI: "mongodb://db:27017"
    depends_on:
      - db

  db:
    image: mongo
    volumes:
      - recipes_db_volume:/data/db
    environment:
      MONGO_INITDB_DATABASE: recipes

volumes:
  recipes_db_volume:
