name: Check formatting (Go)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]


jobs:

  check_formatting:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: "1.20"

    - name: Check formatting
      run: FMT_FILES=$(gofmt -l .) && echo $FMT_FILES && test -z $FMT_FILES
